[alembic]
script_location = migrations
sqlalchemy.url = postgresql+asyncpg://flowvy:flowvy_dev@localhost:5432/flowvy

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = [migrate] %(asctime)s.%(msecs)03d %(levelname)-5.5s [Database] %(message)s
datefmt = %Y-%m-%d %H:%M:%S
