services:
  migrate:
    environment:
      BOT_TOKEN: ""
      WEBAPP_URL: ""
      WEBHOOK_URL: ""
      TELEGRAM_WEBHOOK_SECRET: ""
      REMNAWAVE_URL: ""
      REMNAWAVE_API_TOKEN: ""
      REMNAWAVE_WEBHOOK_SECRET: ""

  app:
    environment:
      BOT_TOKEN: ""
      WEBAPP_URL: ""
      WEBHOOK_URL: ""
      TELEGRAM_WEBHOOK_SECRET: ""
      REMNAWAVE_URL: ""
      REMNAWAVE_API_TOKEN: ""
      REMNAWAVE_WEBHOOK_SECRET: ""
